// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDoc.Context;

namespace RegistroDoc.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20191201191441_InventoryVolumen")]
    partial class InventoryVolumen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistroDoc.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SYS_INASES_INV_INVENTORY_INVENTORY_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bald")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_BALD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Box")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_BOX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentObservation")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_DOCUMENT_OBSERVATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTitle")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_DOCUMENT_TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtremeDates")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_EXTREME_DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallationUnit")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_INSTALLATION_UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_NUMBER")
                        .HasColumnType("int");

                    b.Property<string>("NumberSheets")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_NUMBER_SHEETS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProducerName")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_PRODUCER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_REFERENCE_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondNumber")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_SECOND_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_SERIES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shelf")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_SHELF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateConservation")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_STATE_CONVERSATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume")
                        .HasColumnName("SYS_INASES_INV_INVENTORY_VOLUMEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryId");

                    b.ToTable("SYS_INASES_INV_INVENTORY");
                });

            modelBuilder.Entity("RegistroDoc.Entities.Movements", b =>
                {
                    b.Property<int>("MovementsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SYS_INASES_INV_MOVEMENTS_MOVEMENT_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InventoryId")
                        .HasColumnName("SYS_INASES_INV_MOVEMENTS_INVENTORY_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnName("SYS_INASES_INV_MOVEMENTS_MOVEMENT_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementObservation")
                        .HasColumnName("SYS_INASES_INV_MOVEMENTS_MOVEMENT_OBSERVATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovementType")
                        .HasColumnName("SYS_INASES_INV_MOVEMENTS_MOVEMENT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovementsId");

                    b.HasIndex("InventoryId");

                    b.ToTable("SYS_INASES_INV_MOVEMENTS");
                });

            modelBuilder.Entity("RegistroDoc.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SYS_INASES_INV_ROLE_ROLE_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleDescription")
                        .HasColumnName("SYS_INASES_INV_ROLE_ROLE_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleValue")
                        .HasColumnName("SYS_INASES_INV_ROLE_ROLE_VALUE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("SYS_INASES_INV_ROLE");
                });

            modelBuilder.Entity("RegistroDoc.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("SYS_INASES_INV_USER_USER_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasColumnName("SYS_INASES_INV_USER_ACCOUNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("SYS_INASES_INV_USER_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnName("SYS_INASES_INV_USER_FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnName("SYS_INASES_INV_USER_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnName("SYS_INASES_INV_USER_PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnName("SYS_INASES_INV_USER_ROLE_ID")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .HasColumnName("SYS_INASES_INV_USER_SECOND_LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("SYS_INASES_INV_USER");
                });

            modelBuilder.Entity("RegistroDoc.Entities.Movements", b =>
                {
                    b.HasOne("RegistroDoc.Entities.Inventory", "Inventory")
                        .WithMany("Movements")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroDoc.Entities.User", b =>
                {
                    b.HasOne("RegistroDoc.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
